baseurl = "http://demo.themefisher.com/orbitor-hugo/"
disqusShortname = "themefisher-template"
googleAnalytics = "UA-168676797-1"
languageCode = "en-us"
paginate = 4
summaryLength = "10"
theme = "orbitor-hugo"
themesDir = "../.."
title = "Enterprise technology for Calgary based freelancers and smb's"
[[menu.company]]
name = "About"
url = "about"
weight = 2
[[menu.company]]
name = "Portfolio"
url = "portfolio"
weight = 3
[[menu.company]]
name = "Service"
url = "service"
weight = 4
[[menu.company]]
name = "Blog"
url = "blog"
weight = 5
[[menu.company]]
name = "Contact"
url = "contact"
weight = 6
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Portfolio"
url = "portfolio"
weight = 3
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 4
[[menu.main]]
name = "Blog"
parent = "Pages"
url = "blog"
[[menu.main]]
name = "Service"
parent = "Pages"
url = "service"
[[menu.main]]
name = "Pricing"
parent = "Pages"
url = "pricing"
[[menu.main]]
name = "Contact"
url = "contact"
weight = 5
[[menu.support]]
name = "About"
url = "about"
weight = 1
[[menu.support]]
name = "Portfolio"
url = "portfolio"
weight = 2
[[menu.support]]
name = "Service"
url = "service"
weight = 3
[[menu.support]]
name = "Blog"
url = "blog"
weight = 4
[[menu.support]]
name = "Contact"
url = "contact"
weight = 5
[outputs]
home = ["HTML", "JSON"]
[params]
author = "Chris Connelly"
copyright = "Design and Developed by Chris Connelly"
description = "web design, ecommerce, calgary, marketing, ad agency, advertising firm, alberta, website design, graphic designer, branding, identity, blue, ocean, interactive, marketing, chrisconnelly sem, smo, ppc, seo"
email = "me@chrisconnelly.dev"
footer_content = "Located in Calgary, Alberta, Blue Ocean Interactive Marketing creates online marketing strategies that enable your business to grow.\n\nOur customized marketing solutions combine creative ideas & the latest technologies that solve your unique business needs."
location = "North Main Street,Brooklyn Australia"
logo = "images/logo.png"
logo_white = "images/logo-w.png"
mobile = "+14038310028"
[params.cookies]
enable = false
expire_days = 2
[params.navigation_button]
enable = true
label = "Get an estimate"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify/css/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Montserrat:wght@700;900&family=Rubik&display=swap"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
